package org.bob.learn.client.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.bob.learn.client.dao.model.DeviceOnline;

@Mapper
public interface DeviceOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ONLINE
     *
     * @mbg.generated Mon Jun 10 17:07:19 CST 2019
     */
    int insert(DeviceOnline record);

    int update(DeviceOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVICE_ONLINE
     *
     * @mbg.generated Mon Jun 10 17:07:19 CST 2019
     */
    List<DeviceOnline> selectAll();

    void deleteAll();
}