#Server Config
server:
  port: 8000
#Spring Config
spring:
  application:
    name: learn-client
  redis:
    cluster:
      max-redirects: 3
      nodes: 192.168.4.4:6379,192.168.4.4:6380,192.168.4.4:6381,192.168.4.4:6382,192.168.4.4:6383,192.168.4.4:6384
    lettuce:
      pool:
        min-idle: 64
        max-idle: 64
        max-wait: 500
        max-active: 100
    password: learn

#Feign Config
feign:
  hystrix:
    enabled: true
  httpclient:
    disable-ssl-validation: true
  client:
    default:
      connectTimeout: 1000
      readTimeout: 1000
      encoder: feign.jackson.JacksonEncoder
      decoder: feign.jackson.JacksonDecoder
    courseApiService:
      readTimeout: 500
#Loging Config
logging:
  level:
    root: INFO
#Api Url Config
api:
  url:
    course: sdfasdf
