#Server Config
server:
  port: 8000
#Spring Config
spring:
  application:
    name: learn-client
  kafka:
    bootstrap-servers: 115.159.2.51:9092,118.89.146.110:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 2
  redis:
    cluster:
      max-redirects: 3
      nodes: 115.159.2.51:6379
    lettuce:
      pool:
        min-idle: 8
        max-idle: 64
        max-wait: 2000
        max-active: 100
      shutdown-timeout: 10
    password: learn

#Feign Config
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    disable-ssl-validation: true
  client:
    default:
      connectTimeout: 1000
      readTimeout: 1000
      encoder: feign.jackson.JacksonEncoder
      decoder: feign.jackson.JacksonDecoder
    courseApiService:
      readTimeout: 500
#Loging Config
logging:
  level:
    root: INFO
#Api Url Config
api:
  url:
    course: sdfasdf
